name: Python Test

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", ]
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install --with dev
        - name: Run tests
          run: |
            poetry run pytest --cov=qandle --cov-report=html -W error  -W ignore::PendingDeprecationWarning:semantic_version.base -W ignore::DeprecationWarning  -W ignore::pytest_cov.plugin.CovDisabledWarning
        - name: Check formatting
          run: |
            poetry run ruff check --output-format=github

    